# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc97b669fd43d1f785ff5a216591dfc5"
application_url = "https://percent-biblical-valve-virtual.trycloudflare.com"
embedded = true
name = "Complete-outfit"
handle = "complete-outfit"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://percent-biblical-valve-virtual.trycloudflare.com/auth/callback",
  "https://percent-biblical-valve-virtual.trycloudflare.com/auth/shopify/callback",
  "https://percent-biblical-valve-virtual.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "jerry-styles.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
